version: "3.7"

services:
  guestbook.api:
    container_name: guestbook.host
    image: mcr.microsoft.com/dotnet/aspnet:6.0
    depends_on:
      - db
    build:
      context: .
      dockerfile: Shelter.Guestbook/Shelter.Guestbook/Dockerfile
    ports:
    - 5000:80

  db:
    container_name: database.sql
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"