version: "3.7"

services:
  guestbook.api:
    container_name: guestbook-host
    depends_on:
      - db
    build:
      context: .
      dockerfile: Shelter.Guestbook/Shelter.Guestbook/Dockerfile
    ports:
    - 5000:80

  db:
    container_name: database-sql
    image: "mcr.microsoft.com/mssql/server"
    user: '0:0'
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    volumes:
      - mssql-server-linux-data:/var/opt/mssql/data

volumes:
  mssql-server-linux-data: